In [5]:
import numpy as np
a = np.array([0,1,2,3])
print(a)
print(np.arange(10))

[0 1 2 3]
[0 1 2 3 4 5 6 7 8 9]


In [6]:
#1-D

a = np.array([0, 1, 2, 3])

a

array([0, 1, 2, 3])

In [7]:
a.ndim

1

In [8]:
a.shape

(4,)

In [9]:
len(a)

4

In [11]:
b = np.array([[1,2,3],[4,5,6]])
b

array([[1, 2, 3],
       [4, 5, 6]])

In [12]:
b.shape

(2, 3)

In [13]:
b.ndim

2

In [18]:
len(b)

2

In [24]:
my_list = [1,\
2, 3\
,4,5\
]
print(my_list)

[1, 2, 3, 4, 5]


In [25]:
c = np.array([[[0, 1], [2, 3]], [[4, 5], [6, 7]]])

c

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [26]:
c.ndim

3

In [28]:
c.shape

(2, 2, 2)

In [29]:
len(c)

2

In [30]:
a = np.arange(10) 
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [31]:
b = np.arange(1, 10, 2) #start, end (exclusive), step

b

array([1, 3, 5, 7, 9])

In [32]:
#using linspace

a = np.linspace(0, 1, 6) #start, end, number of points

a

array([0. , 0.2, 0.4, 0.6, 0.8, 1. ])

In [33]:
#common arrays

a = np.ones((3, 3))

a

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [34]:
b = np.zeros((3, 3))

b

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [35]:
c = np.eye(3)  #Return a 2-D array with ones on the diagonal and zeros elsewhere.

c

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [36]:
d = np.eye(3, 2) #3 is number of rows, 2 is number of columns, index of diagonal start with 0

d

array([[1., 0.],
       [0., 1.],
       [0., 0.]])

In [37]:
#create array using diag function

a = np.diag([1, 2, 3, 4]) #construct a diagonal array.

a

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [38]:
np.diag(a)  

array([1, 2, 3, 4])

In [39]:
#create array using random

#Create an array of the given shape and populate it with random samples from a uniform distribution over [0, 1).
a = np.random.rand(4) 

a

array([0.84619148, 0.70455806, 0.89518884, 0.66420083])

In [40]:
a = np.random.randn(4)#Return a sample (or samples) from the “standard normal” distribution.  ***Gausian***

a

array([ 0.42671098,  0.97335626, -0.5409337 , -0.30280743])

In [41]:
a = np.arange(10)

a.dtype

dtype('int64')

In [42]:
#You can explicitly specify which data-type you want:

a = np.arange(10, dtype='float64')
a

array([0., 1., 2., 3., 4., 5., 6., 7., 8., 9.])

In [43]:
a = np.zeros((3, 3))

print(a)

a.dtype

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


dtype('float64')

In [44]:
d = np.array([1+2j, 2+4j])   #Complex datatype

print(d.dtype)

complex128


In [45]:
b = np.array([True, False, True, False])  #Boolean datatype

print(b.dtype)

bool


In [47]:
s = np.array(["Ram", "Robert", "Rahim"])

s.dtype

dtype('<U6')

In [48]:
a = np.arange(10)

print(a[5])  #indices begin at 0, like other Python sequences (and C/C++)

5


In [49]:
a = np.diag([1, 2, 3])

print(a[2, 2])

3


In [50]:
a[2, 1] = 5 #assigning value

a

array([[1, 0, 0],
       [0, 2, 0],
       [0, 5, 3]])

In [51]:
a = np.arange(10)

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [52]:
a[1:8:2] # [startindex: endindex(exclusive) : step]

array([1, 3, 5, 7])

In [53]:
#we can also combine assignment and slicing:

a = np.arange(10)
a[5:] = 10
a

array([ 0,  1,  2,  3,  4, 10, 10, 10, 10, 10])

In [57]:
b = np.arange(5)
a[5:] = b[::1]  #assigning
b
a

array([0, 1, 2, 3, 4, 0, 1, 2, 3, 4])

In [58]:
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [59]:
b = a[::2]
b

array([0, 2, 4, 6, 8])

In [60]:
np.shares_memory(a, b)

True

In [61]:
b[0] = 10
b

array([10,  2,  4,  6,  8])

In [62]:
a

array([10,  1,  2,  3,  4,  5,  6,  7,  8,  9])

In [63]:
a = np.arange(10)

c = a[::2].copy()     #force a copy
c

array([0, 2, 4, 6, 8])

In [64]:
np.shares_memory(a, c)

False

In [65]:
c[0] = 10

a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [67]:
a = np.random.randint(0, 20, 15)
a

array([ 4, 14,  5,  5, 10, 13,  3,  2,  9,  0,  3,  3,  1,  9, 11])

In [68]:
mask = (a % 2 == 0)
extract_from_a = a[mask]

extract_from_a

array([ 4, 14, 10,  2,  0])

In [69]:
a[mask] = -1
a

array([-1, -1,  5,  5, -1, 13,  3, -1,  9, -1,  3,  3,  1,  9, 11])

In [70]:
a = np.arange(0, 100, 10)

a

array([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [71]:
#Indexing can be done with an array of integers, where the same index is repeated several time:

a[[2, 3, 2, 4, 2]]

array([20, 30, 20, 40, 20])

In [72]:
# New values can be assigned 

a[[9, 7]] = -200

a

array([   0,   10,   20,   30,   40,   50,   60, -200,   80, -200])